name: Build and Release

on:
  push:
    branches:
      - '*'
  pull_request:
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: CGO_ENABLED=0 go build -ldflags "-s -w" -trimpath -o node-prune

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: node-prune
          path: node-prune

  